FROM node:18-alpine3.16

# Install dependencies
RUN apk update && \
    apk add --no-cache xdg-utils

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . ./

EXPOSE 3000

CMD npm run start
