name: Backend Tests

on:
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    name: Run Backend Test Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check test results
        if: failure()
        run: exit 1
